### ISSUE TITLE
Deal with issues in ECE_TRADE_C_CEFACT_2018_1E (provisional agenda)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-un#13]
This is from #10 "ECE_TRADE_C_CEFACT_2018_1E.docx".

This is a special kind of document because the numbering of it is from the Agenda, but the structure is a Plenary Document. It's kind of an embedding of a different data structure to the Plenary Document.

From @manuel489 :

1. The source document does not contain numbered paragraphs, nonetheless, the paragraphs in the output are numbered.
2. There are cases where the sections get numbered as if they were paragraphs. This happens when there is no paragraph or subsection at the beginning of the section. I have openned a ticket about it here: https://github.com/metanorma/mn-samples-un/issues/8
3. This document in particular, contains two footnotes directly referenced in the main title. But these don't show up in the output. I have openned a ticket about it here: https://github.com/metanorma/mn-samples-un/issues/9

**Comment by opoudjis** [comment]
The two issues were already closed before this ticket was opened.

**Comment by opoudjis** [comment]
We will have three document types (so far):

* plenary (including all meeting agendas)
* plenary_attachment
* recommendation

The first two have the same cover page. The last two realise paragraph numbering. ECE_TRADE_C_CEFACT_2018_6E is a plenary attachment, not a plenary paper.

Have decided that (lacking other documentation) "Paragraph numbering is enabled for all document types but `plenary`, `agenda`, `budgetary` ". These will also (currently) use the Plenary cover page.

The reason for plenary_attachment is the metadata appearing in the coverpage; we may decide in the future to deal with this differently, decoupling the choice of cover page from the document type.

**Comment by opoudjis** [comment]
Actually, that's silly. We will use only proper document types, and we will switch to the "plenary" cover page if either this is a plenary-type document, or if `:item-number:` or their ilk appear in the document as session metadata.
