### ISSUE TITLE
Numbered introduction in ECE_TRACE_C_CEFACT_2019_26

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-un#14]
Originally from #11 @manuel489 :

ECE_TRACE_C_CEFACT_2019_26 has an "Introduction" section that is numbered (along with its paragraphs). However, in the output doc, the numbering is disabled for this particular section. For example:

![Capture1](https://user-images.githubusercontent.com/33627611/71533322-72a4d300-28ce-11ea-8f97-9cc89c5c1ada.JPG)

I think this means that the "Introduction" here is not considered a preliminary element. Maybe all preliminary elements should be declared instead of detected?

**Comment by opoudjis** [comment]
I've already done this for OGC: https://github.com/metanorma/mn-samples-ogc/issues/21 . Doing here as well.
