### ISSUE TITLE
Issues with ECE_TRADE_C_CEFACT_2019_09

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-un#15]
Originally from #12 @anermina : 

1. Front pages have some differences and the position of the text in header/footer should be adjusted. Currently, docnumber is written in the header of the generated doc, while agenda-id is written in the header of the original document. 
2. In one of the other ECE documents converted earlier, I've noticed that paragraphs weren't numbered (although they were in the original document), so I'm not sure if this should also be applied in this document. [class=steps] doesn't produce numbers in ECE flavour, so currently paragraphs are denoted with a), b), c), etc.
3. Is there a way to restart numbering for the subsections ([start=1] doesn't make any difference)? In the "Blockchain: how it works" section, subsection numbering starts from 4 instead of 1, because the previous section has subsections numbered with 1-3.
4. I'm not sure if it is possible to add line breaks in the items list included in tables. Currently, they are missing in the table in Annex. The word "Annex" is missing before the table, as well.
5. Strikethrough with notation [del]# # is not working in ECE.
6. Numbering of sections on the 3rd level changes from 1., 2., etc. to A., B., etc.
7. There is an extra word "Key" before the footnote text below the image (and it is positioned right after the image, not at the bottom of the page.)

**Comment by opoudjis** [comment]
2: issue resolved by changing document type to plenary-attachment, per https://github.com/metanorma/mn-samples-un/issues/13

**Comment by opoudjis** [comment]
3: Issue seems to have gone away, possibly because the type is now recognised.

**Comment by opoudjis** [comment]
> 4: I'm not sure if it is possible to add line breaks in the items list included in tables. Currently, they are missing in the table in Annex. 

The items list appears to be rendering fine to me; spacing between items in the item list is handled by the stylesheet, but not seeing any call for intervention.

> The word "Annex" is missing before the table, as well.

isodoc suppresses title generation if there is no title; will address.

**Comment by opoudjis** [comment]
5: I can't find the strike through section in the original; in any case, the generic strikethrough notation in Metanorma is `[strike]#strike#`

**Comment by opoudjis** [comment]
6: Issue has gone away.

**Comment by opoudjis** [comment]
7: This is an artifice of Metanorma, inherited from ISO: footnotes of figures are not rendered as footnotes, but as part of the "key" of figures. But the "Key" prefixing it needs to be kept with next paragraph. In any case, this particular behaviour on footnotes should not apply to footnotes on figure titles.

**Comment by opoudjis** [comment]
So we ignore as figure/table footnotes all footnotes on the figure/table caption, and treat them as normal footnotes.

**Comment by opoudjis** [comment]
1: In the Word header, use the agenda id instead of the doc id, if available, and right/left vs centre align accordingly.

**Comment by opoudjis** [comment]
1: "Front pages have some differences ". I'd rather not spend a lot more time on the front page without formal contact about them with UN/ECE.

**Comment by opoudjis** [comment]
@anermina This document should now be processable with updates (involving upstream gems as well).
