### ISSUE TITLE
Fix deployed document.html

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-un#22]
Looks broken right now:

<img width="836" alt="Screen Shot 2020-03-24 at 5 53 40 PM" src="https://user-images.githubusercontent.com/11865/77412106-66121700-6df8-11ea-86e5-398f4766e29d.png">

**Comment by andrew2net** [comment]
@ronaldtse do you mean document identifiers with space on the left?

**Comment by ronaldtse** [comment]
Some of the documents are not showing Titles, and the layout is generally broken...

**Comment by andrew2net** [comment]
> Some of the documents are not showing Titles

Because they don't have Titles in the source.
