### ISSUE TITLE
UN document conversion batch 2

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-un#28]
Here is a new batch of documents provided by @TomasUN (Thank you!!)

* 11 ECE_TRACE_C_CEFACT_2019_27 Brief Semantics+TF.docx (Briefing Note)
* 11 ECE_TRADE_C_CEFACT_2020_18E AGAT PoW.docx (Program of Work)
* 11 ECE_TRADE_C_CEFACT_2020_19E AGAT 1st meeting Report.docx (Meeting report)
* 11E ECE_TRADE_C_CEFACT_2019_22 ToR AG Technologies_Rev1.doc.docx (Terms of Reference)
* FINAL Provisional agenda - ECE_AGAT_2020_INF1.docx (Annotated provisional agenda)

The PDF files are all in `reference-docs`, Word files in https://github.com/metanorma/mn-samples-un-private .

There are few types of documents:

* Briefing Note
* Agenda
* Vision and Mission
* Term of Reference
* Program of Work
* Meeting Report

As described by @TomasUN , 
> Vision and Mission statement is exactly same as PoW just different name, so sometime it’s incorporated into one, as I understand its just shorter “Elevator pitch” of PoW

@metanorma/editors can you help assign yourselves to documents and convert them? Thanks!

**Comment by manuelfuenmayor** [comment]
@ronaldtse , when you say "Item of agenda", does that mean the doctype attribute is agenda (`:doctype: agenda`)?

**Comment by manuelfuenmayor** [comment]
Because, looking at the corresponding documentation: https://www.metanorma.com/author/un/authoring/#document-header-attributes
"Agenda" is the only type that I see from the other ones you've listed.

**Comment by ronaldtse** [comment]
@manuel489 actually ignore the "Item of agenda" part, their doctype is the latter one. I've removed them from the list.

**Comment by manuelfuenmayor** [comment]
Conversion of "Brief Semantics+TF.docx " added in https://github.com/metanorma/mn-samples-un/pull/29

**Comment by manuelfuenmayor** [comment]
For the record, I proposed to @anermina that I could take all of these conversions as they are very short, and she agreed. So, I will fully address this task.

**Comment by manuelfuenmayor** [comment]
Conversion of "AGAT PoW.docx" added in https://github.com/metanorma/mn-samples-un/pull/30

**Comment by manuelfuenmayor** [comment]
Conversions of: "AGAT 1st meeting Report", "ToR AG Technologies_Rev1", "FINAL Provisional agenda", are added in https://github.com/metanorma/mn-samples-un/pull/31

**Comment by manuelfuenmayor** [comment]
All documents are merged. Closing.
