### ISSUE TITLE
Verify front-page footnote issue on ToR AG Technologies_Rev1

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-un#33]
From @manuel489 https://github.com/metanorma/mn-samples-un/pull/31

***Comments on ToR AG Technologies_Rev1:***
- I set `terms-of-reference` as doctype.
- Bug detected. When a footnote is placed in the front page, a blank page is introduced between the front page and the main content. Ticket opened here: https://github.com/metanorma/metanorma-un/issues/53

**Comment by manuelfuenmayor** [comment]
I believe this issue is fixed in https://github.com/metanorma/metanorma-un/issues/53

**Comment by manuelfuenmayor** [comment]
Confirmed, issue fixed. Closing.
