### ISSUE TITLE
Verify agenda doctype and footnotes in title (ECE_AGAT_2020_INF1)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-un#34]
From @manuel489 #31 

***Comments on on ECE_AGAT_2020_INF1:***
- I set `agenda` as doctype.
- This document in particular, has two footnotes directly referenced in the main title:

*Screenshot (original source):*
![capture-title](https://user-images.githubusercontent.com/33627611/79813645-36e4bc00-834a-11ea-9d47-154a95e65376.PNG)

Footnotes don't work in that situation. I opened a ticket about it here: https://github.com/metanorma/metanorma-un/issues/54

**Comment by manuelfuenmayor** [comment]
This issue remains on hold until https://github.com/metanorma/metanorma-un/issues/54 gets fixed.

**Comment by opoudjis** [comment]
I had demoted that issue to Low priority, so I guess it needs to become high again...

**Comment by manuelfuenmayor** [comment]
Confirmed. This issue is fixed. Thanks @opoudjis!
Closing.
